# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-07-20 22:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('valueaccounting', '0013_auto_20180530_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('changed_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('agent_subclass', models.CharField(choices=[(b'Person', 'Person'), (b'Organization', 'Organization')], default=b'Person', max_length=16, verbose_name='subclass')),
                ('image', models.URLField(blank=True, null=True, verbose_name='image')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_agents_changed', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_agents_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VocabAgentRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('changed_date', models.DateField(auto_now=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships_changed', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('in_scope_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='valueaccounting.VocabAgent', verbose_name='scope')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_relationships', to='valueaccounting.VocabAgent', verbose_name='object')),
            ],
            options={
                'ordering': ('subject',),
            },
        ),
        migrations.CreateModel(
            name='VocabAgentRelationshipRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('changed_date', models.DateField(auto_now=True, null=True)),
                ('role_label', models.CharField(max_length=255, verbose_name='label')),
                ('inverse_role_label', models.CharField(blank=True, max_length=255, null=True, verbose_name='inverse label')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_changed', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'ordering': ('role_label',),
            },
        ),
        migrations.CreateModel(
            name='VocabMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_numerical_value', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='numerical value')),
            ],
            options={
                'ordering': ('has_unit',),
            },
        ),
        migrations.CreateModel(
            name='VocabPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('changed_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('due', models.DateTimeField(blank=True, null=True, verbose_name='due')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans_changed', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VocabProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('changed_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('has_beginning', models.DateTimeField(blank=True, null=True, verbose_name='beginning')),
                ('has_end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('finished', models.BooleanField(default=False, verbose_name='finished')),
                ('classified_as', models.TextField(blank=True, null=True, verbose_name='classified as')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_processes_changed', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_processes_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('in_scope_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='valueaccounting.VocabAgent', verbose_name='scope')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='valueaccounting.VocabPlan', verbose_name='plan')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VocabUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('changed_date', models.DateField(auto_now=True, null=True)),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('symbol', models.CharField(blank=True, max_length=255, null=True, verbose_name='symbol')),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.AddField(
            model_name='vocabmeasure',
            name='has_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='valueaccounting.VocabUnit', verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='vocabagentrelationship',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='valueaccounting.VocabAgentRelationshipRole', verbose_name='relationship'),
        ),
        migrations.AddField(
            model_name='vocabagentrelationship',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_relationships', to='valueaccounting.VocabAgent', verbose_name='subject'),
        ),
    ]
