# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-07-22 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0015_auto_20210721_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabresourcespecification',
            name='defaultUnitOfEffort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_specifications_effort', to='valueaccounting.VocabUnit', verbose_name='default unit of effort'),
        ),
        migrations.AlterField(
            model_name='vocabresourcespecification',
            name='defaultUnitOfResource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_specifications_resource', to='valueaccounting.VocabUnit', verbose_name='default unit of resource'),
        ),
    ]
