# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-07-23 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0016_auto_20210722_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabresourcespecification',
            name='defaultUnitOfEffort',
        ),
        migrations.RemoveField(
            model_name='vocabresourcespecification',
            name='defaultUnitOfResource',
        ),
        migrations.AddField(
            model_name='vocabresourcespecification',
            name='default_unit_of_effort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_specifications_effort', to='valueaccounting.VocabUnit', verbose_name='default unit of effort'),
        ),
        migrations.AddField(
            model_name='vocabresourcespecification',
            name='default_unit_of_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_specifications_resource', to='valueaccounting.VocabUnit', verbose_name='default unit of resource'),
        ),
    ]
