# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-07-23 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0017_auto_20210723_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabresourcespecification',
            old_name='resourceClassifiedAs',
            new_name='resource_classified_as',
        ),
    ]
